version: '2'
services:
  gemfire:
    #image: "apachegeode/geode"
    build:
     context: ./docker
     dockerfile: gemfire-Dockerfile
    ports:
     - "8080:8080"
     - "10334:10334"
     - "40404:40404"
     - "1099:1099"
     - "7070:7070"
    volumes:
     - .:/code
    tty: true
  gpdb:
    image: "pivotaldata/gpdb-base"
    ports:
     - "5432:5432"
     - "5005:5005"
     - "5010:5010"
     - "9022:22"
     - "40000:40000"
     - "40001:40001"
     - "40002:40002"
    expose:
     - "5432"
    volumes:
     - .:/code
    links:
     - gemfire
    tty: true

